/**
 * Auto-generated sidebars
 *
 * This configuration uses Docusaurus's autogenerated sidebar feature
 * to create navigation based on the folder structure.
 */

module.exports = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};
